---
rbac:
  create: true
controller:
  stats:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true
        prometheus.io/port: "10254"
  extraArgs:
    v: 2
